POST http://localhost:8080/code/run
Accept: application/json
Content-Type: application/json

{
  "user_address": "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  "code": "def sum_two_smallest_numbers(numbers):\n    numbers.sort()\n    return numbers[0] + numbers[1]\n",
  "kata_id": "0"
}